// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUVb5YjX1sMalWdr10cLRMHF9OTvbnls',
    appId: '1:996966102384:web:ddada55e07ef4b75e0cbb5',
    messagingSenderId: '996966102384',
    projectId: 'shop-app-ac632',
    authDomain: 'shop-app-ac632.firebaseapp.com',
    storageBucket: 'shop-app-ac632.appspot.com',
    measurementId: 'G-E3M9HQ4JZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_okvysPBUzP8aToSAeWLBpY2X6Mj12A',
    appId: '1:996966102384:android:2946af1a002c1fbae0cbb5',
    messagingSenderId: '996966102384',
    projectId: 'shop-app-ac632',
    storageBucket: 'shop-app-ac632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1p_du5iOzF5T5hX9gcaMSgNm5K5MKFGQ',
    appId: '1:996966102384:ios:d2a1885a67af6c01e0cbb5',
    messagingSenderId: '996966102384',
    projectId: 'shop-app-ac632',
    storageBucket: 'shop-app-ac632.appspot.com',
    iosClientId: '996966102384-9d3k2aaprfdaqvmm40sr6ck4mppvp905.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1p_du5iOzF5T5hX9gcaMSgNm5K5MKFGQ',
    appId: '1:996966102384:ios:d2a1885a67af6c01e0cbb5',
    messagingSenderId: '996966102384',
    projectId: 'shop-app-ac632',
    storageBucket: 'shop-app-ac632.appspot.com',
    iosClientId: '996966102384-9d3k2aaprfdaqvmm40sr6ck4mppvp905.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
